# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 05:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('account_kit_id', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('animation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_address', models.URLField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='LearnedVerb',
            fields=[
                ('learned_verb_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('correct', models.BooleanField()),
                ('tries', models.IntegerField()),
                ('animations', models.ManyToManyField(to='api.Animation')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_dt', models.DateField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('verb_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verb', models.CharField(max_length=20)),
                ('definition', models.TextField()),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='VerbPack',
            fields=[
                ('verb_pack_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=260)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='VerbVentureUser',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='verbpack',
            name='user_verb_packs',
            field=models.ManyToManyField(to='api.VerbVentureUser'),
        ),
        migrations.AddField(
            model_name='verbpack',
            name='verb_pack_verbs',
            field=models.ManyToManyField(to='api.Verb'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.VerbVentureUser'),
        ),
        migrations.AddField(
            model_name='session',
            name='session_students',
            field=models.ManyToManyField(to='api.Student'),
        ),
        migrations.AddField(
            model_name='learnedverb',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Session'),
        ),
        migrations.AddField(
            model_name='learnedverb',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
        ),
        migrations.AddField(
            model_name='learnedverb',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Verb'),
        ),
        migrations.AddField(
            model_name='animation',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Verb'),
        ),
        migrations.AddField(
            model_name='admin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.VerbVentureUser'),
        ),
    ]
