# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='admin',
            name='account_kit_id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
