# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_learnedverb_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='verbpack',
            name='title',
            field=models.CharField(default='default verb pack', max_length=260),
            preserve_default=False,
        ),
    ]
