# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171108_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='account_kit_id',
            new_name='accountKitId',
        ),
        migrations.RenameField(
            model_name='animation',
            old_name='animation_id',
            new_name='animationId',
        ),
        migrations.RenameField(
            model_name='animation',
            old_name='image_address',
            new_name='imageAddress',
        ),
        migrations.RenameField(
            model_name='learnedverb',
            old_name='created_dt',
            new_name='createdDt',
        ),
        migrations.RenameField(
            model_name='learnedverb',
            old_name='learned_verb_id',
            new_name='learnedVerbId',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_dt',
            new_name='sessionDt',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_id',
            new_name='sessionId',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_students',
            new_name='sessionStudents',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='studentId',
        ),
        migrations.RenameField(
            model_name='verb',
            old_name='verb_id',
            new_name='verbId',
        ),
        migrations.RenameField(
            model_name='verbpack',
            old_name='user_verb_packs',
            new_name='userVerbPacks',
        ),
        migrations.RenameField(
            model_name='verbpack',
            old_name='verb_pack_id',
            new_name='verbPackId',
        ),
        migrations.RenameField(
            model_name='verbpack',
            old_name='verb_pack_verbs',
            new_name='verbPackVerbs',
        ),
        migrations.RenameField(
            model_name='verbventureuser',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='verbventureuser',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='verbventureuser',
            old_name='user_id',
            new_name='userId',
        ),
    ]
