# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_verb_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnedverb',
            name='animations',
            field=models.ManyToManyField(to='api.Animation'),
        ),
    ]
